### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [MudBlazor/LanguageResource](https://hosted.weblate.org/projects/mudblazor/language-resource/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by henon** [comment]
@meenzen do you know why the PR fails?

**Comment by meenzen** [comment]
Not sure, I'll have a look later.

**Comment by ScarletKuro** [comment]
Shouldn't it be `zh-Hans` for Simplified, and `zh-Hant` for Traditional? I see it has `zh-SIMPLIFIED`

**Comment by henon** [comment]
> Shouldn't it be `zh-Hans` for Simplified, and `zh-Hant` for Traditional? I see it has `zh-SIMPLIFIED`

That would make sense.

**Comment by henon** [comment]
I removed zh_SIMPLIFIED after downloading the resx then added zh_Hans and uploaded the file again. Now it looks better.

**Comment by meenzen** [comment]
Weblate nicely splits commits based on the language and authors. I only see the squash merge option, can we disable that for this repo?

**Comment by ScarletKuro** [comment]
> Weblate nicely splits commits based on the language and authors. I only see the squash merge option, can we disable that for this repo?

Sure

**Pull request merged**
